stages:
  - test
  - build
  - deploy

clazy:
  stage: test
  image: kaidan/debian-unstable
  variables:
    CMAKE_CXX_COMPILER: clazy
  script: utils/travis/build.sh
  allow_failure: true

qmllint:
  stage: test
  image: kaidan/neon-bionic
  script: qmllint $(find . -name "*.qml")
  variables:
    QT_SELECT: 5

neon-bionic:
  stage: build
  image: kaidan/neon-bionic
  script: utils/travis/build.sh

debian-sid:
  stage: build
  image: kaidan/debian-unstable
  script: utils/travis/build.sh

archlinux:
  stage: build
  image: kaidan/archlinux
  script: utils/travis/build.sh

linux-appimage:
  stage: deploy
  image: kaidan/ubuntu-xenial
  script: utils/build-linux-appimage.sh
  variables:
    QXMPP_BUILD: /usr
  artifacts:
    paths:
      - "*.AppImage"
      - "*.AppImage.zsync"
    expire_in: 1 week

windows-mxe:
  stage: deploy
  image: kaidan/windows-mxe
  script:
    - utils/build-windows-mxe.sh
    - mv build/bin/kaidan.exe kaidan.exe
  allow_failure: true
  artifacts:
    paths:
      - "kaidan.exe"
    expire_in: 1 week

android:
  stage: deploy
  image: kdeorg/android-sdk
  script:
    - utils/build-android-docker.sh
  variables:
    KF5_VERSION: master
  allow_failure: true
  artifacts:
    paths:
      - "kaidan_build_apk-debug.apk"
    expire_in: 1 week

mac-osxcross:
  stage: deploy
  image: kaidan/mac-osxcross
  script:
    - utils/build-mac-osxcross.sh
    - tar -cf kaidan.tar -C build/bin/ kaidan.app
  allow_failure: true
  artifacts:
    paths:
      - "kaidan.tar"
    expire_in: 1 week

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_SYSTEM: cmake
  BUILD_TYPE: Release
