# SPDX-FileCopyrightText: 2018 Jonah Brüchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: CC0-1.0

include:
  - project: lnj/craft-ci
    ref: work/lnj/keep-signing-logs-test
    file: /gitlab-templates/macos-arm64-qt6.yml

craft_macos_qt6_arm64:
  rules:
    - when: always
