# SPDX-FileCopyrightText: 2018 Jonah Brüchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: CC0-1.0

flatpak:
  variables:
    KDE_FLATPAK_APP_ID: im.kaidan.kaidan

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_SYSTEM: cmake
  BUILD_TYPE: Release

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/clang-format.yml
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/yaml-lint.yml
      - /gitlab-templates/json-validation.yml
      - /gitlab-templates/xml-lint.yml
      - /gitlab-templates/flatpak.yml
      - /gitlab-templates/linux.yml
      - /gitlab-templates/freebsd.yml
      # - /gitlab-templates/android.yml
      # - /gitlab-templates/windows.yml
      - /gitlab-templates/craft-windows-x86-64.yml
