# SPDX-FileCopyrightText: 2018 Jonah Brüchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: CC0-1.0

stages:
  - build
  - deploy

clazy:
  stage: build
  image: ghcr.io/kaidanim/debian
  variables:
    CMAKE_CXX_COMPILER: clazy
  script: utils/travis/build.sh
  allow_failure: true

qmllint:
  stage: build
  image: ghcr.io/kaidanim/debian
  script: qmllint $(find . -name "*.qml")
  variables:
    QT_SELECT: 5

xmllint:
  stage: build
  image: ghcr.io/kaidanim/debian
  script:
    - apt update && apt install -y libxml2-utils && xmllint --noout $(find . -type f -name *.xml -or -name *.xml.in)

build:
  stage: build
  image: ghcr.io/kaidanim/debian
  script: utils/travis/build.sh

flatpak:
  variables:
    KDE_FLATPAK_APP_ID: im.kaidan.kaidan

linux-appimage:
  stage: deploy
  image: kaidan/ubuntu-xenial
  script: utils/build-linux-appimage.sh
  variables:
    QXMPP_BUILD: /usr
  artifacts:
    paths:
      - "*.AppImage"
      - "*.AppImage.zsync"
    expire_in: 1 week
  only:
    - network/kaidan

android:
  stage: deploy
  image: kdeorg/android-sdk
  script:
    - utils/build-android-docker.sh
  variables:
    KF5_VERSION: master
  allow_failure: true
  artifacts:
    paths:
      - "kaidan_arm.apk"
      - "kaidan_arm64.apk"
    expire_in: 1 week
  only:
    - network/kaidan

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_SYSTEM: cmake
  BUILD_TYPE: Release

include:
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/reuse-lint.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/flatpak.yml
