# SPDX-FileCopyrightText: 2023 Plata Hill <plata.hill@kdemail.net>
# SPDX-License-Identifier: CC0-1.0

Dependencies:
  - 'on':
      - '@all'
    require:
      frameworks/extra-cmake-modules: '@stable'
      frameworks/kcoreaddons: '@stable'
      frameworks/kio: '@stable'
      frameworks/kirigami: '@stable'
      libraries/kirigami-addons: '@stable'
      libraries/kquickimageeditor: '@stable'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
