# SPDX-FileCopyrightText: 2023 Plata Hill <plata.hill@kdemail.net>
#
# SPDX-License-Identifier: CC0-1.0

Dependencies:
  - 'on': ['@all']
    require:
      frameworks/extra-cmake-modules: '@latest-kf6'
      frameworks/kcoreaddons: '@latest-kf6'
      frameworks/kio: '@latest-kf6'
      frameworks/kirigami: '@latest-kf6'
      frameworks/prison: '@latest-kf6'
      libraries/kirigami-addons: '@latest-kf6'
      libraries/kquickimageeditor: '@latest-kf6'
      libraries/qxmpp: '@latest-kf6'

  - 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
    require:
      'frameworks/kcrash': '@latest-kf6'
      'frameworks/kwindowsystem': '@latest-kf6'

Options:
  require-passing-tests-on: ['@all']
  clang-format-versions: [19]
