# SPDX-FileCopyrightText: 2026 Linus Jahn <lnj@kaidan.im>
#
# SPDX-License-Identifier: CC0-1.0

# QML files of the im.kaidan.kaidan module, relative to this directory
set(KAIDAN_QML_FILES
    AboutDialog.qml
    AboutPage.qml
    CallPage.qml
    ChatPage.qml
    EmptyChatPage.qml
    GlobalDrawer.qml
    ImageBackgroundPage.qml
    Main.qml
    QrCodeOnboardingPage.qml
    RosterPage.qml
    StartPage.qml
    details/AccountDetailsContent.qml
    details/AccountDetailsDialog.qml
    details/AccountDetailsHeader.qml
    details/AccountDetailsPage.qml
    details/AccountKeyAuthenticationButton.qml
    details/AvatarChangePage.qml
    details/ContactDetailsContent.qml
    details/ContactDetailsDialog.qml
    details/ContactDetailsPage.qml
    details/ContactKeyAuthenticationButton.qml
    details/DetailsContent.qml
    details/DetailsDialog.qml
    details/DetailsHeader.qml
    details/DetailsPage.qml
    details/GroupChatDetailsContent.qml
    details/GroupChatDetailsDialog.qml
    details/GroupChatDetailsHeader.qml
    details/GroupChatDetailsPage.qml
    details/GroupChatUserKeyAuthenticationButton.qml
    details/KeyAuthenticationButton.qml
    details/MediaOverview.qml
    details/NotesChatDetailsContent.qml
    details/NotesChatDetailsDialog.qml
    details/NotesChatDetailsHeader.qml
    details/NotesChatDetailsPage.qml
    details/ProviderChatDetailsContent.qml
    details/ProviderChatDetailsDialog.qml
    details/ProviderChatDetailsHeader.qml
    details/ProviderChatDetailsPage.qml
    details/RosterItemDetailsContent.qml
    details/RosterItemDetailsDialog.qml
    details/RosterItemDetailsHeader.qml
    details/RosterItemDetailsPage.qml
    details/SpecialRosterItemDetailsHeader.qml
    details/UserDevicesArea.qml
    details/UserKeyAuthenticationButton.qml
    elements/AboutContent.qml
    elements/AboutHeader.qml
    elements/AccountKeyAuthenticationPage.qml
    elements/AccountQrCode.qml
    elements/AccountRelatedAvatar.qml
    elements/AccountSelectionDialog.qml
    elements/Audio.qml
    elements/Avatar.qml
    elements/BlockingReportContent.qml
    elements/BlockingReportDialog.qml
    elements/BusyIndicatorFormButton.qml
    elements/Button.qml
    elements/CameraArea.qml
    elements/CameraStatus.qml
    elements/CenteredAdaptiveButton.qml
    elements/CenteredAdaptiveText.qml
    elements/ChatHintArea.qml
    elements/ChatInfo.qml
    elements/ChatMessage.qml
    elements/ChatMessageContextMenu.qml
    elements/ChatMessageContextMenuButton.qml
    elements/ChatPageSendingPane.qml
    elements/CircleProgressBar.qml
    elements/ClickableItemDelegate.qml
    elements/ConfirmationArea.qml
    elements/ConfirmationFormButtonArea.qml
    elements/ContactAdditionContent.qml
    elements/ContactAdditionDialog.qml
    elements/ContactAdditionPage.qml
    elements/ContactAdditionQrCodePage.qml
    elements/ContactDelegate.qml
    elements/ContactInvitationHintDelegate.qml
    elements/ContactKeyAuthenticationPage.qml
    elements/ContactQrCode.qml
    elements/CopyFormTextDelegate.qml
    elements/CustomConnectionSettings.qml
    elements/DataForm.qml
    elements/Dialog.qml
    elements/DisabledAccountHint.qml
    elements/EmojiPicker.qml
    elements/EncryptionKeysArea.qml
    elements/ExplainedContentPage.qml
    elements/ExplanationArea.qml
    elements/ExplanationOptionsTogglePage.qml
    elements/ExplanationTogglePage.qml
    elements/ExtendedMessageContent.qml
    elements/FormAdditionButton.qml
    elements/FormComboBoxDelegate.qml
    elements/FormExpansionButton.qml
    elements/FormExpansionButtonBackground.qml
    elements/FormExpansionButtonDelegate.qml
    elements/FormIconButton.qml
    elements/FormInfoContent.qml
    elements/FormInfoDialog.qml
    elements/FormInfoHeader.qml
    elements/FormInfoPage.qml
    elements/FormattedTextArea.qml
    elements/FormattedTextEdit.qml
    elements/GeoLocationInteractiveMap.qml
    elements/GeoLocationMap.qml
    elements/GeoLocationMapPage.qml
    elements/GeoLocationMapPreview.qml
    elements/GeoLocationPreview.qml
    elements/GeoLocationSharingPage.qml
    elements/GroupChatCreationContent.qml
    elements/GroupChatCreationDialog.qml
    elements/GroupChatCreationPage.qml
    elements/GroupChatInvitation.qml
    elements/GroupChatInviteeDelegate.qml
    elements/GroupChatJoiningContent.qml
    elements/GroupChatJoiningDialog.qml
    elements/GroupChatJoiningPage.qml
    elements/GroupChatParticipantPicker.qml
    elements/GroupChatQrCode.qml
    elements/GroupChatUserDelegate.qml
    elements/GroupChatUserKeyAuthenticationPage.qml
    elements/HighlightedFormButtonBackground.qml
    elements/HorizontalSeparator.qml
    elements/IconButton.qml
    elements/IconButtonArea.qml
    elements/ImageBackground.qml
    elements/ImageCaptureDialog.qml
    elements/InlineListView.qml
    elements/InteractiveBackground.qml
    elements/ItemDelegateSelectionMarker.qml
    elements/KeyAuthenticationPage.qml
    elements/ListViewSearchField.qml
    elements/ListViewSectionDelegate.qml
    elements/LoadingArea.qml
    elements/LoadingStackArea.qml
    elements/LoginArea.qml
    elements/LoginQrCode.qml
    elements/MediaPlayerControl.qml
    elements/MediaViewer.qml
    elements/MediaViewerDialog.qml
    elements/MediaViewerPage.qml
    elements/MediumMessagePreview.qml
    elements/MediumMouseArea.qml
    elements/MediumPreview.qml
    elements/MediumSendingPreview.qml
    elements/MediumTransferProgressBar.qml
    elements/MessageBackground.qml
    elements/MessageCounter.qml
    elements/MessageReactionAdditionButton.qml
    elements/MessageReactionButton.qml
    elements/MessageReactionDetailsButton.qml
    elements/MessageReactionDetailsDialog.qml
    elements/MessageReactionDisplayButton.qml
    elements/MessageReactionEmojiPicker.qml
    elements/MessageReactionRetryButton.qml
    elements/NewMediaDialog.qml
    elements/NonInteractiveFormDelegateBackground.qml
    elements/OpacityChangingMouseArea.qml
    elements/ProviderFilterArea.qml
    elements/PublicGroupChatSearchDialog.qml
    elements/QrCodeScanner.qml
    elements/QrCodeScanningArea.qml
    elements/RecordingIndicator.qml
    elements/ReferencedMessage.qml
    elements/RosterFilterArea.qml
    elements/RosterItemDelegate.qml
    elements/RoundedImage.qml
    elements/RoundedRectangle.qml
    elements/ScalableText.qml
    elements/SearchBarPage.qml
    elements/SecondaryFormButtonBackground.qml
    elements/SelectablePreview.qml
    elements/SelectionMarker.qml
    elements/ShutterRelease.qml
    elements/SimpleListViewSearchField.qml
    elements/Slider.qml
    elements/SliderBackground.qml
    elements/Status.qml
    elements/TextButton.qml
    elements/TextCompleter.qml
    elements/TextCompleterView.qml
    elements/ToolbarCallButton.qml
    elements/UrlFormButtonDelegate.qml
    elements/UserKeyAuthenticationPage.qml
    elements/VideoRecordingDialog.qml
    elements/ZoomSlider.qml
    elements/fields/Field.qml
    elements/fields/JidField.qml
    elements/fields/PasswordField.qml
    elements/fields/RegistrationPasswordField.qml
    registration/AutomaticRegistrationPage.qml
    registration/CustomDataFormCard.qml
    registration/ManualRegistrationPage.qml
    registration/ProviderPage.qml
    registration/RegistrationButton.qml
    registration/RegistrationPage.qml
    registration/RegistrationRequestPage.qml
    registration/WebRegistrationPage.qml
)
